// Auto-generated by scripts/extractConnectors.ts — do not edit manually.
// Re-run the script if OBJ files change.

export interface PieceConnectorAnchors {
  endpoints: [[number, number], [number, number]];
  bbox: { minX: number; maxX: number; minY: number; maxY: number };
}

export const CONNECTOR_ANCHORS: Record<number, PieceConnectorAnchors> = {
  // Piece J (id=0) — 11887 vertices, span: 28.383714 x 17.605304
  0: {
    endpoints: [[-37.938949, -32.734319], [-9.555235, -15.129015]],
    bbox: { minX: -41.026215, maxX: -4.572814, minY: -34.14439, maxY: -8.361632 },
  },
  // Piece C (id=1) — 12488 vertices, span: 43.567434 x 0.11592
  1: {
    endpoints: [[-37.025381, -37.018965], [6.542053, -37.134885]],
    bbox: { minX: -41.026218, maxX: 10.620626, minY: -49.347187, maxY: -34.244427 },
  },
  // Piece H (id=2) — 12337 vertices, span: 35.338931 x 3.517915
  2: {
    endpoints: [[17.081997, -50.210897], [52.420928, -46.692982]],
    bbox: { minX: 15.252814, maxX: 56.229012, minY: -60.01783, maxY: -34.244427 },
  },
  // Piece B (id=3) — 14334 vertices, span: 35.583443 x 5.372084
  3: {
    endpoints: [[-21.836272, -52.411642], [13.747171, -47.039558]],
    bbox: { minX: -25.823421, maxX: 15.152778, minY: -75.22998, maxY: -38.776577 },
  },
  // Piece A (id=4) — 14180 vertices, span: 34.986527 x 34.948083
  4: {
    endpoints: [[17.471717, -117.095766], [52.458244, -82.147683]],
    bbox: { minX: 15.252813, maxX: 56.229012, minY: -120.82901, maxY: -79.852814 },
  },
  // Piece K (id=5) — 15067 vertices, span: 2.755811 x 34.816143
  5: {
    endpoints: [[-46.452874, -42.655487], [-43.697063, -77.47163]],
    bbox: { minX: -56.238369, maxX: -30.45561, minY: -79.752777, maxY: -38.792004 },
  },
  // Piece I (id=6) — 14411 vertices, span: 25.325514 x 43.931555
  6: {
    endpoints: [[-27.791511, -57.881183], [-2.465997, -101.812738]],
    bbox: { minX: -30.355574, maxX: -0.050018, minY: -105.626221, maxY: -53.979374 },
  },
  // Piece G (id=7) — 14945 vertices, span: 29.987159 x 8.832328
  7: {
    endpoints: [[23.475658, -63.613797], [53.462817, -72.446125]],
    bbox: { minX: 19.77561, maxX: 56.229015, minY: -79.752777, maxY: -49.447224 },
  },
  // Piece D (id=8) — 14306 vertices, span: 4.431666 x 42.723117
  8: {
    endpoints: [[11.84604, -116.426069], [16.277706, -73.702952]],
    bbox: { minX: 0.050019, maxX: 25.832777, minY: -120.82901, maxY: -69.202538 },
  },
  // Piece F (id=9) — 16045 vertices, span: 41.297531 x 31.535645
  9: {
    endpoints: [[-52.416495, -82.299576], [-11.118964, -113.835221]],
    bbox: { minX: -56.229015, maxX: -4.572814, minY: -120.838371, maxY: -79.852814 },
  },
  // Piece E (id=10) — 14255 vertices, span: 43.625979 x 0.149102
  10: {
    endpoints: [[-6.555164, -31.221897], [37.070815, -31.370999]],
    bbox: { minX: -10.620625, maxX: 41.026218, minY: -34.14439, maxY: -8.36163 },
  },
};
